print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/a240015/Documents/GitHub/Semester-2-Assessment/Assets/Animations/New stuff/Goober.mb"`)
{		
	file -o "C:/Users/a240015/Documents/GitHub/Semester-2-Assessment/Assets/Animations/New stuff/Goober.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/a240015/Documents/GitHub/Semester-2-Assessment/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/a240015/Documents/GitHub/Semester-2-Assessment/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/a240015/Documents/GitHub/Semester-2-Assessment/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
